# Generated by Django 5.2 on 2025-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_customer_email_payment_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('CDEK', 'СДЭК'), ('YANDEX', 'Яндекс Доставка'), ('BOXBERY', 'Boxberry')], max_length=20, null=True),
        ),
    ]
